kind: pipeline
name: default

platform:
  os: linux
  arch: arm

steps:
  - name: test
    image: rust:1.33
    commands:
      - cargo build --verbose --all
      - cargo test --verbose --all -- --test-threads=1
