kind: pipeline
name: default

steps:
  - name: test
    image: rust:1.33
    commands:
      - cargo build --verbose --all
      - cargo test --verbose --all -- --test-threads=1

  - name: containerize
    image: plugins/docker
    settings:
      repo: alebeck/yocto
      auto_tag: true
      username: alebeck
      password:
        from_secret: docker_password